"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "tanggal_mutasi", label: "Tanggal", render: (r: any) => <span className="font-medium">{r.tanggal_mutasi}</span> },
  { key: "jenis_mutasi", label: "Jenis" },
  { key: "keterangan", label: "Keterangan" },
]

const fields = [
  { name: "jenis_mutasi" as const, label: "Jenis Mutasi", type: "number" as const },
  { name: "tanggal_mutasi" as const, label: "Tanggal Mutasi", type: "date" as const },
  { name: "keterangan" as const, label: "Keterangan", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Mutasi C-Desa"
      endpoint="/api/cdesa_mutasi"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
