"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "nomor", label: "Nomor", render: (r: any) => <span className="font-medium">{r.nomor}</span> },
  { key: "nama_kepemilikan", label: "Nama Pemilik" },
]

const fields = [
  { name: "nomor" as const, label: "Nomor", type: "text" as const, required: true },
  { name: "nama_kepemilikan" as const, label: "Nama Kepemilikan", type: "text" as const, required: true },
  { name: "jenis_pemilik" as const, label: "Jenis Pemilik", type: "checkbox" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="C-Desa"
      endpoint="/api/cdesa_rincian"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
