"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "judul", label: "Judul", render: (r: any) => <span className="font-medium">{r.judul}</span> },
  { key: "jenis_widget", label: "Jenis" },
  { key: "urut", label: "Urut" },
]

const fields = [
  { name: "judul" as const, label: "Judul", type: "text" as const, required: true },
  { name: "enis_widget" as const, label: "Jenis Widget", type: "number" as const },
  { name: "urut" as const, label: "Urut", type: "number" as const },
  { name: "form_admin" as const, label: "Form Admin", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Widget"
      endpoint="/api/web_widget"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
