"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "key", label: "Key", render: (r: any) => <span className="font-medium">{r.key}</span> },
  { key: "value", label: "Value" },
  { key: "keterangan", label: "Keterangan" },
]

const fields = [
  { name: "key" as const, label: "Key", type: "text" as const, required: true },
  { name: "value" as const, label: "Value", type: "text" as const },
  { name: "keterangan" as const, label: "Keterangan", type: "text" as const },
  { name: "urut" as const, label: "Urut", type: "number" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Setting Aplikasi"
      endpoint="/api/setting_aplikasi"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
