"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "keterangan", label: "Keterangan", render: (r: any) => <span className="font-medium">{r.keterangan}</span> },
]

const fields = [
  { name: "keterangan" as const, label: "Keterangan", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Log Activity"
      endpoint="/api/tools"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
