"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "judul", label: "Judul", render: (r: any) => <span className="font-medium">{r.judul}</span> },
  { key: "tanggal", label: "Tanggal" },
  { key: "status", label: "Status" },
]

const fields = [
  { name: "judul" as const, label: "Judul", type: "text" as const, required: true },
  { name: "tanggal" as const, label: "Tanggal", type: "date" as const },
  { name: "status" as const, label: "Status", type: "checkbox" as const },
  { name: "keterangan" as const, label: "Keterangan", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Pemilihan"
      endpoint="/api/pemilihan"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.uuid}
    />
  )
}
