import { prisma } from "@/lib/prisma"
import { makeCollection } from "@/lib/crud"
// CRUD generated by batch generator
export const { GET, POST, DELETE } = makeCollection(prisma.kehadiran_perangkat_desa, { orderBy: { id: "desc" as any } })
