"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "SenderNumber", label: "Pengirim", render: (r: any) => <span className="font-medium">{r.SenderNumber}</span> },
  { key: "TextDecoded", label: "Pesan" },
]

const fields = [
  { name: "SenderNumber" as const, label: "Pengirim", type: "text" as const },
  { name: "TextDecoded" as const, label: "Pesan", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Mailbox"
      endpoint="/api/mailbox"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.ID}
    />
  )
}
