import { prisma } from "@/lib/prisma"
import Manager from "./Manager"
// CRUD generated by batch generator
export const dynamic = "force-dynamic"

export default async function Page() {
  const data = await prisma.inbox.findMany({ orderBy: { ID: "desc" }, take: 100 })
  return <Manager initial={data} />
}
