"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "ip_address", label: "IP", render: (r: any) => <span className="font-medium">{r.ip_address}</span> },
  { key: "keterangan", label: "Keterangan" },
  { key: "status", label: "Status" },
]

const fields = [
  { name: "ip_address" as const, label: "IP Address", type: "text" as const, required: true },
  { name: "keterangan" as const, label: "Keterangan", type: "text" as const },
  { name: "status" as const, label: "Status", type: "checkbox" as const },
  { name: "keyboard" as const, label: "Keyboard", type: "checkbox" as const },
  { name: "orientasi_layar" as const, label: "Orientasi Layar", type: "checkbox" as const },
  { name: "mac_address" as const, label: "MAC Address", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Anjungan"
      endpoint="/api/anjungan"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
