"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "nama", label: "Nama", render: (r: any) => <span className="font-medium">{r.nama}</span> },
  { key: "sasaran", label: "Sasaran" },
]

const fields = [
  { name: "nama" as const, label: "Nama", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Statistik Bantuan"
      endpoint="/api/statistik_bantuan"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
