"use server"

import { prisma } from "@/lib/prisma"
import { makeActions } from "@/lib/actions"
// CRUD generated by batch generator
export const { create, update, delete: del } = makeActions({ delegate: prisma.kehadiran_hari_libur, path: "/buku_umum", keyField: "id" })
