"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "tanggal", label: "Tanggal", render: (r: any) => <span className="font-medium">{r.tanggal}</span> },
  { key: "keterangan", label: "Keterangan" },
]

const fields = [
  { name: "tanggal" as const, label: "Tanggal", type: "date" as const, required: true },
  { name: "keterangan" as const, label: "Keterangan", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Buku Umum / Hari Libur"
      endpoint="/api/buku_umum"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
