"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "judul", label: "Judul", render: (r: any) => <span className="font-medium">{r.judul}</span> },
  { key: "icon", label: "Icon" },
  { key: "status", label: "Status" },
]

const fields = [
  { name: "judul" as const, label: "Judul", type: "text" as const, required: true },
  { name: "icon" as const, label: "Icon", type: "text" as const },
  { name: "raw_query" as const, label: "Raw Query", type: "text" as const },
  { name: "warna" as const, label: "Warna", type: "text" as const },
  { name: "urut" as const, label: "Urut", type: "number" as const },
  { name: "status" as const, label: "Status", type: "checkbox" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Shortcut"
      endpoint="/api/shortcut"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
