"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "nama_barang", label: "Nama Barang", render: (r: any) => <span className="font-medium">{r.nama_barang}</span> },
  { key: "kondisi_bangunan", label: "Kondisi" },
  { key: "letak", label: "Letak" },
]

const fields = [
  { name: "nama_barang" as const, label: "Nama Barang", type: "text" as const, required: true },
  { name: "kondisi_bangunan" as const, label: "Kondisi Bangunan", type: "text" as const },
  { name: "luas_bangunan" as const, label: "Luas Bangunan", type: "number" as const },
  { name: "letak" as const, label: "Letak", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Inventaris Konstruksi"
      endpoint="/api/inventaris_kontruksi"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
