"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "description", label: "Keterangan", render: (r: any) => <span className="font-medium">{r.description}</span> },
  { key: "created_at", label: "Tanggal" },
]

const fields = [
  { name: "description" as const, label: "Keterangan", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Optimasi Gambar"
      endpoint="/api/optimasi_gambar"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
