"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "id_kk", label: "ID KK", render: (r: any) => <span className="font-medium">{r.id_kk}</span> },
  { key: "tgl_peristiwa", label: "Tanggal" },
]

const fields = [
  { name: "catatan" as const, label: "Catatan", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Log Keluarga"
      endpoint="/api/periksa_log_keluarga"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
