"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "id_pend", label: "ID Penduduk", render: (r: any) => <span className="font-medium">{r.id_pend}</span> },
  { key: "kode_peristiwa", label: "Peristiwa" },
]

const fields = [
  { name: "catatan" as const, label: "Catatan", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Log Penduduk"
      endpoint="/api/periksa"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
