import { prisma } from "@/lib/prisma"
import { auth } from "@/lib/auth"
import { NextResponse } from "next/server"
// CRUD generated by batch generator - custom for tweb_penduduk_mandiri (id_pend PK)

export async function GET(req: Request) {
  const url = new URL(req.url)
  const page = parseInt(url.searchParams.get("page") ?? "1")
  const perPage = 20
  const q = url.searchParams.get("q") ?? ""
  const where: any = q ? { OR: [{ nik: { contains: q } }] } : {}
  const [data, total] = await Promise.all([
    prisma.tweb_penduduk_mandiri.findMany({ where, orderBy: { id_pend: "desc" }, skip: (page - 1) * perPage, take: perPage }),
    prisma.tweb_penduduk_mandiri.count({ where }),
  ])
  return NextResponse.json({ data, total, page, perPage })
}

export async function POST(req: Request) {
  const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  const body = await req.json(); const created = await prisma.tweb_penduduk_mandiri.create({ data: body }); return NextResponse.json(created)
}

export async function DELETE(req: Request) {
  const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  let body: any = {}; try { body = await req.json() } catch {}
  if (body.ids?.length) await prisma.tweb_penduduk_mandiri.deleteMany({ where: { id_pend: { in: body.ids } } })
  return NextResponse.json({ ok: true })
}
