"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "authenticatable_type", label: "Tipe", render: (r: any) => <span className="font-medium">{r.authenticatable_type}</span> },
  { key: "password", label: "Password" },
  { key: "expires_at", label: "Kadaluwarsa" },
]

const fields = [
  { name: "password" as const, label: "Password", type: "text" as const },
  { name: "expires_at" as const, label: "Kadaluwarsa", type: "date" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="OTP"
      endpoint="/api/otp"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
