"use server"

import { prisma } from "@/lib/prisma"
import { makeActions } from "@/lib/actions"
// CRUD generated by batch generator
export const { create, update, delete: del } = makeActions({ delegate: prisma.mutasi_inventaris_tanah, path: "/inventaris_tanah_mutasi", keyField: "id" })
