"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "jenis_mutasi", label: "Jenis Mutasi", render: (r: any) => <span className="font-medium">{r.jenis_mutasi}</span> },
  { key: "tahun_mutasi", label: "Tahun" },
  { key: "keterangan", label: "Keterangan" },
]

const fields = [
  { name: "jenis_mutasi" as const, label: "Jenis Mutasi", type: "text" as const },
  { name: "tahun_mutasi" as const, label: "Tahun Mutasi", type: "date" as const },
  { name: "keterangan" as const, label: "Keterangan", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Mutasi Inventaris Tanah"
      endpoint="/api/inventaris_tanah_mutasi"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
