"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "tahun", label: "Tahun", render: (r: any) => <span className="font-medium">{r.tahun}</span> },
  { key: "anggaran", label: "Anggaran" },
]

const fields = [
  { name: "tahun" as const, label: "Tahun", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Laporan Keuangan"
      endpoint="/api/laporan"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
