import { prisma } from "@/lib/prisma"
import { makeCollection } from "@/lib/crud"
// CRUD generated by batch generator
export const { GET, POST, DELETE } = makeCollection(prisma.anjungan, { search: ["ip_address", "keterangan"], orderBy: { id: "desc" as any } })
