"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "penduduk_id", label: "Penduduk ID", render: (r: any) => <span className="font-medium">{r.penduduk_id}</span> },
]

const fields = [
  { name: "penduduk_id" as const, label: "Penduduk ID", type: "number" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Layanan Mandiri"
      endpoint="/api/mandiri"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
