"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "kode", label: "Kode", render: (r: any) => <span className="font-medium">{r.kode}</span> },
  { key: "nama", label: "Nama" },
]

const fields = [
  { name: "kode" as const, label: "Kode", type: "text" as const, required: true },
  { name: "nama" as const, label: "Nama", type: "text" as const, required: true },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Klasifikasi Surat"
      endpoint="/api/periksa_klasifikasi_surat"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
