"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "judul", label: "Judul", render: (r: any) => <span className="font-medium">{r.judul}</span> },
  { key: "isi", label: "Isi" },
  { key: "status", label: "Status" },
]

const fields = [
  { name: "judul" as const, label: "Judul", type: "text" as const, required: true },
  { name: "isi" as const, label: "Isi", type: "text" as const },
  { name: "kode" as const, label: "Kode", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Notifikasi"
      endpoint="/api/notif"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
