"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "tanggal", label: "Tanggal", render: (r: any) => <span className="font-medium">{r.tanggal}</span> },
  { key: "status_kehadiran", label: "Status" },
]

const fields = [
  { name: "tanggal" as const, label: "Tanggal", type: "date" as const },
  { name: "status_kehadiran" as const, label: "Status Kehadiran", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Kehadiran Perangkat Desa"
      endpoint="/api/kehadiran"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
