import { prisma } from "@/lib/prisma"
import { auth } from "@/lib/auth"
import { NextResponse } from "next/server"
// CRUD generated by batch generator - custom for sasaran_paud (id_sasaran_paud PK)

export async function GET(req: Request) {
  const url = new URL(req.url)
  const page = parseInt(url.searchParams.get("page") ?? "1")
  const perPage = 20
  const [data, total] = await Promise.all([
    prisma.sasaran_paud.findMany({ orderBy: { id_sasaran_paud: "desc" }, skip: (page - 1) * perPage, take: perPage }),
    prisma.sasaran_paud.count(),
  ])
  return NextResponse.json({ data, total, page, perPage })
}

export async function POST(req: Request) {
  const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  const body = await req.json(); const created = await prisma.sasaran_paud.create({ data: body }); return NextResponse.json(created)
}

export async function DELETE(req: Request) {
  const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  let body: any = {}; try { body = await req.json() } catch {}
  if (body.ids?.length) await prisma.sasaran_paud.deleteMany({ where: { id_sasaran_paud: { in: body.ids } } })
  return NextResponse.json({ ok: true })
}
