import { prisma } from "@/lib/prisma"
import { auth } from "@/lib/auth"
import { NextResponse } from "next/server"
// CRUD generated by batch generator - custom for sasaran_paud (id_sasaran_paud PK)

export async function GET(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const item = await prisma.sasaran_paud.findUnique({ where: { id_sasaran_paud: parseInt(id) } })
  if (!item) return NextResponse.json({ error: "Not found" }, { status: 404 }); return NextResponse.json(item)
}

export async function PUT(req: Request, { params }: { params: Promise<{ id: string }> }) {
  const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  const { id } = await params; const body = await req.json()
  const updated = await prisma.sasaran_paud.update({ where: { id_sasaran_paud: parseInt(id) }, data: body }); return NextResponse.json(updated)
}

export async function DELETE(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  const { id } = await params; await prisma.sasaran_paud.delete({ where: { id_sasaran_paud: parseInt(id) } }); return NextResponse.json({ ok: true })
}
