"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "identifier", label: "Identifier", render: (r: any) => <span className="font-medium">{r.identifier}</span> },
  { key: "purpose", label: "Purpose" },
  { key: "expires_at", label: "Kadaluwarsa" },
]

const fields = [
  { name: "identifier" as const, label: "Identifier", type: "text" as const, required: true },
  { name: "purpose" as const, label: "Purpose", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Token OTP"
      endpoint="/api/token"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
