"use server"

import { prisma } from "@/lib/prisma"
import { makeActions } from "@/lib/actions"
// CRUD generated by batch generator
export const { create, update, delete: del } = makeActions({ delegate: prisma.sasaran_paud, path: "/stunting_rekapitulasi", keyField: "id_sasaran_paud" })
