"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "kelompok", label: "Kelompok", render: (r: any) => <span className="font-medium">{r.kelompok}</span> },
  { key: "deskripsi", label: "Deskripsi" },
]

const fields = [
  { name: "kelompok" as const, label: "Kelompok", type: "text" as const, required: true },
  { name: "deskripsi" as const, label: "Deskripsi", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Master Kelompok"
      endpoint="/api/kelompok_master"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
