"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "nomor", label: "Nomor", render: (r: any) => <span className="font-medium">{r.nomor}</span> },
  { key: "luas_persil", label: "Luas" },
  { key: "lokasi", label: "Lokasi" },
]

const fields = [
  { name: "nomor" as const, label: "Nomor", type: "text" as const, required: true },
  { name: "luas_persil" as const, label: "Luas Persil", type: "number" as const },
  { name: "lokasi" as const, label: "Lokasi", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Data Persil"
      endpoint="/api/data_persil"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
