"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"
import { StatusLabel } from "@/components/admin/Ui"

const columns = [
  { key: "nama", label: "Nama", render: (r: any) => <span className="font-medium">{r.nama}</span> },
  { key: "simbol", label: "Simbol" },
  { key: "color", label: "Warna", render: (r: any) => r.color ? <span style={{ color: r.color }}><i className="fa fa-circle" /> {r.color}</span> : "-" },
  { key: "tipe", label: "Tipe", render: (r: any) => r.tipe === 1 ? "Padat" : r.tipe === 2 ? "Putus-putus" : r.tipe ?? "-" },
  { key: "tebal", label: "Tebal" },
  { key: "enabled", label: "Status", render: (r: any) => <StatusLabel ok={r.enabled === 1} /> },
]

const fields = [
  { name: "nama" as const, label: "Nama", type: "text" as const, required: true },
  { name: "simbol" as const, label: "Simbol", type: "text" as const },
  { name: "color" as const, label: "Warna", type: "text" as const },
  { name: "tipe" as const, label: "Tipe", type: "select" as const, options: [
    { value: 0, label: "Solid" },
    { value: 1, label: "Padat" },
    { value: 2, label: "Putus-putus" },
  ] },
  { name: "tebal" as const, label: "Tebal", type: "number" as const },
  { name: "jenis" as const, label: "Jenis Garis", type: "text" as const },
  { name: "enabled" as const, label: "Aktif", type: "checkbox" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="GIS Line"
      endpoint="/api/line"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
