import { prisma } from "@/lib/prisma"
import { makeCollection } from "@/lib/crud"
// CRUD generated by batch generator
export const { GET, POST, DELETE } = makeCollection(prisma.widget, { search: ["judul"], orderBy: { id: "desc" as any } })
