"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "nama", label: "Nama", render: (r: any) => <span className="font-medium">{r.nama}</span> },
  { key: "versi", label: "Versi" },
  { key: "status", label: "Status" },
]

const fields = [
  { name: "nama" as const, label: "Nama", type: "text" as const, required: true },
  { name: "slug" as const, label: "Slug", type: "text" as const },
  { name: "versi" as const, label: "Versi", type: "text" as const },
  { name: "status" as const, label: "Status", type: "checkbox" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Theme"
      endpoint="/api/theme"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
