"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "nama_grup", label: "Nama Grup", render: (r: any) => <span className="font-medium">{r.nama_grup}</span> },
  { key: "keterangan", label: "Keterangan" },
]

const fields = [
  { name: "nama_grup" as const, label: "Nama Grup", type: "text" as const, required: true },
  { name: "keterangan" as const, label: "Keterangan", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Grup Kontak"
      endpoint="/api/grup_kontak"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id_grup}
    />
  )
}
