"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "nama", label: "Nama", render: (r: any) => <span className="font-medium">{r.nama}</span> },
  { key: "kategori", label: "Kategori" },
  { key: "tgl_upload", label: "Tgl Upload" },
]

const fields = [
  { name: "nama" as const, label: "Nama", type: "text" as const, required: true },
  { name: "kategori" as const, label: "Kategori", type: "number" as const },
  { name: "satuan" as const, label: "Satuan", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Dokumen Web"
      endpoint="/api/dokumen_web"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
