"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "nama_barang", label: "Nama Barang", render: (r: any) => <span className="font-medium">{r.nama_barang}</span> },
  { key: "kode_barang", label: "Kode Barang" },
  { key: "harga", label: "Harga" },
]

const fields = [
  { name: "nama_barang" as const, label: "Nama Barang", type: "text" as const, required: true },
  { name: "kode_barang" as const, label: "Kode Barang", type: "text" as const },
  { name: "harga" as const, label: "Harga", type: "number" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Inventaris Asset"
      endpoint="/api/inventaris_master"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
