"use client"
// CRUD generated by batch generator
import CrudManager from "@/components/admin/CrudManager"

const columns = [
  { key: "nama_desa", label: "Nama Desa", render: (r: any) => <span className="font-medium">{r.nama_desa}</span> },
  { key: "kode_desa", label: "Kode Desa" },
]

const fields = [
  { name: "nama_desa" as const, label: "Nama Desa", type: "text" as const },
]

export default function Manager({ initial }: { initial?: any[] }) {
  return (
    <CrudManager
      title="Status Desa"
      endpoint="/api/status_desa"
      columns={columns}
      fields={fields}
      rowKey={(r) => r.id}
    />
  )
}
